<a href="https://colab.research.google.com/github/ufukhurriyetoglu/vector-normalization-for-vector-search/blob/main/vector_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --user annoy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.5/647.5 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for annoy: filename=annoy-1.17.3-cp310-cp310-linux_x86_64.whl size=552446 sha256=cf626a46021c5e9b5a23282740b341bd70b624fe0a438f5ddf46ff56f899b915
  Stored in directory: /root/.cache/pip/wheels/64/8a/da/f714bcf46c5efdcfcac0559e63370c21abe961c48e3992465a
Successfully built annoy


In [1]:
from annoy import AnnoyIndex
import random

f = 40  # Length of item vector that will be indexed

t = AnnoyIndex(f, 'angular')
for i in range(1000):
    v = [random.gauss(0, 1) for z in range(f)]
    t.add_item(i, v)

t.build(10) # 10 trees
t.save('test.ann')

u = AnnoyIndex(f, 'angular')
u.load('test.ann') # super fast, will just mmap the file
print(u.get_nns_by_item(0, 15)) # will find the 1000 nearest neighbors

[0, 374, 638, 650, 123, 977, 755, 300, 796, 49, 840, 412, 314, 105, 37]


In [2]:
t.get_item_vector(0)

[-0.18866823613643646,
 -0.9645815491676331,
 0.34515419602394104,
 -0.28188851475715637,
 -1.2084115743637085,
 0.7380104660987854,
 0.569412887096405,
 0.4931466281414032,
 -3.1470351219177246,
 0.8047766089439392,
 1.1071109771728516,
 0.7642222046852112,
 -0.07716409862041473,
 1.2649691104888916,
 1.161159634590149,
 0.8700860738754272,
 -0.17273437976837158,
 0.4998491406440735,
 -0.21158505976200104,
 -0.13357938826084137,
 0.7548620104789734,
 0.93825763463974,
 -0.4266389310359955,
 -1.2948094606399536,
 -1.066059947013855,
 1.5857605934143066,
 -0.4173220098018646,
 0.9549368023872375,
 -1.4187403917312622,
 -0.46681803464889526,
 -2.10677433013916,
 -0.5007885098457336,
 -0.13498055934906006,
 1.5397776365280151,
 1.5640982389450073,
 -0.551122784614563,
 -1.5541023015975952,
 -1.4084750413894653,
 -0.5537386536598206,
 -0.04934476688504219]

In [3]:
t.get_item_vector(777)

[1.101402997970581,
 -1.0245754718780518,
 -0.44516441226005554,
 -0.44058334827423096,
 -0.4735833704471588,
 0.2958965003490448,
 -1.3189730644226074,
 0.708330512046814,
 -0.2142573893070221,
 0.10182296484708786,
 -0.5372434854507446,
 -0.9184718728065491,
 0.9615828990936279,
 -1.2419862747192383,
 0.49988481402397156,
 -0.31989043951034546,
 1.4256510734558105,
 0.14656339585781097,
 -0.3560389578342438,
 -1.1493494510650635,
 0.9224896430969238,
 1.497171401977539,
 -0.585648238658905,
 -0.4694666564464569,
 1.7036086320877075,
 -0.7013132572174072,
 0.03552623838186264,
 -0.5104782581329346,
 -0.40729066729545593,
 1.018438458442688,
 -0.08560502529144287,
 -1.221710443496704,
 -1.39047110080719,
 0.6960083842277527,
 -0.4867105484008789,
 0.19080452620983124,
 -1.105360507965088,
 1.6838734149932861,
 0.6841000914573669,
 0.32218262553215027]

Does not provide much intuition, lets consider a smaller subset of vectors

In [55]:
vectors = [
    [0.3, 0.4],
    [3.1, 4.2],
    [4.0, 3.0],
    [4.0, 5.0],
    [8.0, 10.0],
    [6.1, 8.1],
    [15.2, 20.3],
    [18.2, 24.3],
    [36.5, 48.3]
]

In [56]:
# lets create the annoy index for vectors collection

In [57]:
length_of_vector = 2

In [58]:
t_angular = AnnoyIndex(length_of_vector, 'angular')
t_euclidean = AnnoyIndex(length_of_vector, 'euclidean')

In [59]:
for i, vector in enumerate(vectors):
  t_angular.add_item(i, vector)
  t_euclidean.add_item(i, vector)

In [60]:
t_angular.build(3) # 10 trees
t_angular.save('test_angular.ann')

u_angular = AnnoyIndex(length_of_vector, 'angular')
u_angular.load('test_angular.ann')

True

In [61]:
t_euclidean.build(3) # 10 trees
t_euclidean.save('test_euclidean.ann')

u_euclidean = AnnoyIndex(length_of_vector, 'euclidean')
u_euclidean.load('test_euclidean.ann')

True

In [62]:
counter = 0
print("For the vector [0.3, 0.4]")
for item_index in u_angular.get_nns_by_item(0, 5):
  print(f"{counter}th  neighbor: ")
  print(vectors[item_index])
  counter+=1
  print()

For the vector [0.3, 0.4]
0th  neighbor: 
[0.3, 0.4]

1th  neighbor: 
[18.2, 24.3]

2th  neighbor: 
[15.2, 20.3]

3th  neighbor: 
[6.1, 8.1]

4th  neighbor: 
[36.5, 48.3]



In [63]:
counter = 0
print("For the vector [0.3, 0.4]")
for item_index in u_euclidean.get_nns_by_item(0, 5):
  print(f"{counter}th  neighbor: ")
  print(vectors[item_index])
  counter+=1
  print()

For the vector [0.3, 0.4]
0th  neighbor: 
[0.3, 0.4]

1th  neighbor: 
[4.0, 3.0]

2th  neighbor: 
[3.1, 4.2]

3th  neighbor: 
[4.0, 5.0]

4th  neighbor: 
[6.1, 8.1]



In [65]:
## Lets see what happens after normalization

# we will use L2-normalization first

In [66]:
import numpy as np

To normalize a vector, you can divide each element of the vector by its magnitude. This will result in a vector with a length or magnitude of 1, also known as a unit vector. Normalizing a vector preserves its original direction while adjusting its magnitude.

Here's an example of how to normalize a vector using NumPy:

In [68]:


# Create a vector
vector = np.array([3, 4])


In [69]:
# Calculate the magnitude of the vector
magnitude = np.linalg.norm(vector)

In [70]:
magnitude

5.0

In [71]:
# Normalize the vector
normalized_vector = vector / magnitude

print("Normalized Vector:", normalized_vector)

Normalized Vector: [0.6 0.8]


In [72]:
# lets create python functions to be able to observe better

In [73]:
def calculate_magnitude(vector):
  return np.linalg.norm(vector)

In [75]:
calculate_magnitude([0.3, 0.4])

0.5

In [76]:
calculate_magnitude([18, 24])

30.0

In [77]:
def normalize_vector(vector):
  return vector / calculate_magnitude(vector)

In [78]:
normalize_vector([0.3, 0.4])

array([0.6, 0.8])

In [79]:
normalize_vector([18, 24])

array([0.6, 0.8])

In [80]:
## !yay normalized forms are equal for [0.3, 0.4] and [18, 24], because both construct 3-4-5 triangle in terms of vector space

In [81]:
# lets normalize the vectors collection

In [82]:
normalized_vectors = [normalize_vector(vector) for vector in vectors]

In [83]:
normalized_vectors

[array([0.6, 0.8]),
 array([0.5938523 , 0.80457408]),
 array([0.8, 0.6]),
 array([0.62469505, 0.78086881]),
 array([0.62469505, 0.78086881]),
 array([0.60157674, 0.79881501]),
 array([0.5993689 , 0.80047294]),
 array([0.59947286, 0.80039508]),
 array([0.60290319, 0.79781436])]

In [93]:
# lets write a modular annoy index builder

def create_annoy_index(distance_metric, vector_length, vectors):
  index_name = "_".join(["index", distance_metric])
  annoy_index = AnnoyIndex(vector_length, distance_metric)
  for i, vector in enumerate(vectors):
    annoy_index.add_item(i, vector)
  annoy_index.build(3)
  annoy_index.save(index_name)
  reloaded_annoy_index = AnnoyIndex(vector_length, distance_metric)
  reloaded_annoy_index.load(index_name)
  return reloaded_annoy_index

In [105]:
normalized_vectors_angular_distance_annoy_index = create_annoy_index("angular", 2, normalized_vectors)
original_vectors_angular_distance_annoy_index = create_annoy_index("angular", 2, vectors)

In [111]:
normalized_vectors_dot_distance_annoy_index = create_annoy_index("dot", 2, normalized_vectors)
original_vectors_dot_distance_annoy_index = create_annoy_index("dot", 2, vectors)

In [106]:
normalized_vectors_euclidean_distance_annoy_index = create_annoy_index("euclidean", 2, normalized_vectors)
original_vectors_euclidean_distance_annoy_index = create_annoy_index("euclidean", 2, vectors)

In [107]:
original_vectors_angular_distance_annoy_index.get_nns_by_item(0, 5)

[0, 7, 6, 5, 8]

In [108]:
normalized_vectors_angular_distance_annoy_index.get_nns_by_item(0, 5)

[0, 7, 6, 5, 8]

In [109]:
normalized_vectors_euclidean_distance_annoy_index.get_nns_by_item(0, 5)

[0, 7, 6, 5, 8]

In [110]:
original_vectors_euclidean_distance_annoy_index.get_nns_by_item(0, 5)

[0, 2, 1, 3, 5]

In [112]:
original_vectors_dot_distance_annoy_index.get_nns_by_item(0, 5)

[8, 7, 6, 4, 5]

In [114]:
normalized_vectors_dot_distance_annoy_index.get_nns_by_item(0, 5)

[0, 7, 6, 5, 8]